# Use root/example as user/password credentials
version: '3.1'

services:
MYSQL_IMAGE=mysql:8.0.24
MYSQL_DBNAME=example-db
MYSQL_PASSWORD=password
MSQL_PORT=5432
  mysql:
    image: ${MYSQL_IMAGE}
    command: --default-authentication-plugin=mysql_native_password
    restart: unless_stoped
    environment:
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysqlvolume:/var/lib/mysql
    ports:
      - "${MSQL_PORT}:3306"

volumes:
  mysqlvolume: